# Generated by Django 3.0.3 on 2022-03-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=500)),
                ('purpose', models.CharField(max_length=500)),
            ],
        ),
    ]
